/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHadistRouteImport } from './routes/_authenticated/hadist'
import { Route as AuthenticatedDoaHarianRouteImport } from './routes/_authenticated/doa-harian'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedHadistBookIdRouteImport } from './routes/_authenticated/hadist.$bookId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHadistRoute = AuthenticatedHadistRouteImport.update({
  id: '/hadist',
  path: '/hadist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoaHarianRoute = AuthenticatedDoaHarianRouteImport.update({
  id: '/doa-harian',
  path: '/doa-harian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHadistBookIdRoute =
  AuthenticatedHadistBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthenticatedHadistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AuthenticatedChatRoute
  '/doa-harian': typeof AuthenticatedDoaHarianRoute
  '/hadist': typeof AuthenticatedHadistRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/hadist/$bookId': typeof AuthenticatedHadistBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof AuthenticatedChatRoute
  '/doa-harian': typeof AuthenticatedDoaHarianRoute
  '/hadist': typeof AuthenticatedHadistRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/hadist/$bookId': typeof AuthenticatedHadistBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/doa-harian': typeof AuthenticatedDoaHarianRoute
  '/_authenticated/hadist': typeof AuthenticatedHadistRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/hadist/$bookId': typeof AuthenticatedHadistBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/doa-harian'
    | '/hadist'
    | '/profile'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/hadist/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/doa-harian'
    | '/hadist'
    | '/profile'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/hadist/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/chat'
    | '/_authenticated/doa-harian'
    | '/_authenticated/hadist'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/hadist/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hadist': {
      id: '/_authenticated/hadist'
      path: '/hadist'
      fullPath: '/hadist'
      preLoaderRoute: typeof AuthenticatedHadistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doa-harian': {
      id: '/_authenticated/doa-harian'
      path: '/doa-harian'
      fullPath: '/doa-harian'
      preLoaderRoute: typeof AuthenticatedDoaHarianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hadist/$bookId': {
      id: '/_authenticated/hadist/$bookId'
      path: '/$bookId'
      fullPath: '/hadist/$bookId'
      preLoaderRoute: typeof AuthenticatedHadistBookIdRouteImport
      parentRoute: typeof AuthenticatedHadistRoute
    }
  }
}

interface AuthenticatedHadistRouteChildren {
  AuthenticatedHadistBookIdRoute: typeof AuthenticatedHadistBookIdRoute
}

const AuthenticatedHadistRouteChildren: AuthenticatedHadistRouteChildren = {
  AuthenticatedHadistBookIdRoute: AuthenticatedHadistBookIdRoute,
}

const AuthenticatedHadistRouteWithChildren =
  AuthenticatedHadistRoute._addFileChildren(AuthenticatedHadistRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDoaHarianRoute: typeof AuthenticatedDoaHarianRoute
  AuthenticatedHadistRoute: typeof AuthenticatedHadistRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDoaHarianRoute: AuthenticatedDoaHarianRoute,
  AuthenticatedHadistRoute: AuthenticatedHadistRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
